#!/bin/bash
#
# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

VENDOR=razer
DEVICE=aura

# Load extract_utils and do some sanity checks
MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$MY_DIR" ]]; then MY_DIR="$PWD"; fi

LINEAGE_ROOT="$MY_DIR"/../../..

HELPER="$LINEAGE_ROOT"/lineage/build/tools/extract_utils.sh
if [ ! -f "$HELPER" ]; then
    echo "Unable to find helper script at $HELPER"
    exit 1
fi
. "$HELPER"

VENDOR_SKIP_FILES_AURA=(
  "bin/acpi"
  "bin/base64"
  "bin/basename"
  "bin/blockdev"
  "bin/cal"
  "bin/cat"
  "bin/chcon"
  "bin/chgrp"
  "bin/chmod"
  "bin/chown"
  "bin/chroot"
  "bin/chrt"
  "bin/cksum"
  "bin/clear"
  "bin/cmp"
  "bin/comm"
  "bin/cp"
  "bin/cpio"
  "bin/cut"
  "bin/date"
  "bin/dd"
  "bin/df"
  "bin/diff"
  "bin/dirname"
  "bin/dmesg"
  "bin/dos2unix"
  "bin/du"
  "bin/echo"
  "bin/egrep"
  "bin/env"
  "bin/expand"
  "bin/expr"
  "bin/fallocate"
  "bin/false"
  "bin/fgrep"
  "bin/file"
  "bin/find"
  "bin/flock"
  "bin/fmt"
  "bin/free"
  "bin/getenforce"
  "bin/getevent"
  "bin/getprop"
  "bin/groups"
  "bin/gunzip"
  "bin/gzip"
  "bin/head"
  "bin/hostname"
  "bin/hwclock"
  "bin/id"
  "bin/ifconfig"
  "bin/inotifyd"
  "bin/insmod"
  "bin/ionice"
  "bin/iorenice"
  "bin/kill"
  "bin/killall"
  "bin/ln"
  "bin/load_policy"
  "bin/log"
  "bin/logname"
  "bin/losetup"
  "bin/ls"
  "bin/lsmod"
  "bin/lsof"
  "bin/lspci"
  "bin/lsusb"
  "bin/md5sum"
  "bin/microcom"
  "bin/mkdir"
  "bin/mkfifo"
  "bin/mknod"
  "bin/mkswap"
  "bin/mktemp"
  "bin/modinfo"
  "bin/modprobe"
  "bin/more"
  "bin/mount"
  "bin/mountpoint"
  "bin/mv"
  "bin/netstat"
  "bin/newfs_msdos"
  "bin/nice"
  "bin/nl"
  "bin/nohup"
  "bin/od"
  "bin/paste"
  "bin/patch"
  "bin/pgrep"
  "bin/pidof"
  "bin/pkill"
  "bin/pmap"
  "bin/printenv"
  "bin/printf"
  "bin/ps"
  "bin/pwd"
  "bin/readlink"
  "bin/realpath"
  "bin/renice"
  "bin/restorecon"
  "bin/rm"
  "bin/rmdir"
  "bin/rmmod"
  "bin/runcon"
  "bin/sed"
  "bin/sendevent"
  "bin/seq"
  "bin/setenforce"
  "bin/setprop"
  "bin/setsid"
  "bin/sha1sum"
  "bin/sha224sum"
  "bin/sha256sum"
  "bin/sha384sum"
  "bin/sha512sum"
  "bin/sleep"
  "bin/sort"
  "bin/split"
  "bin/start"
  "bin/stat"
  "bin/stop"
  "bin/strings"
  "bin/stty"
  "bin/swapoff"
  "bin/swapon"
  "bin/sync"
  "bin/sysctl"
  "bin/tac"
  "bin/tail"
  "bin/tar"
  "bin/taskset"
  "bin/tee"
  "bin/time"
  "bin/timeout"
  "bin/top"
  "bin/touch"
  "bin/tr"
  "bin/true"
  "bin/truncate"
  "bin/tty"
  "bin/ulimit"
  "bin/umount"
  "bin/uname"
  "bin/uniq"
  "bin/unix2dos"
  "bin/uptime"
  "bin/usleep"
  "bin/uudecode"
  "bin/uuencode"
  "bin/vmstat"
  "bin/wc"
  "bin/which"
  "bin/whoami"
  "bin/xargs"
  "bin/xxd"
  "bin/yes"
  "bin/zcat"
  "etc/selinux/vendor_file_contexts"
  "etc/selinux/nonplat_file_contexts"
  "etc/selinux/nonplat_hwservice_contexts"
  "etc/selinux/nonplat_mac_permissions.xml"
  "etc/selinux/nonplat_property_contexts"
  "etc/selinux/nonplat_seapp_contexts"
  "etc/selinux/nonplat_sepolicy.cil"
  "etc/selinux/nonplat_service_contexts"
  "etc/selinux/plat_sepolicy_vers.txt"
  "etc/selinux/precompiled_sepolicy"
  "etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256"
  "etc/selinux/vndservice_contexts"
  "etc/selinux/plat_pub_versioned.cil"
  "etc/selinux/vendor_hwservice_contexts"
  "etc/selinux/vendor_mac_permissions.xml"
  "etc/selinux/vendor_property_contexts"
  "etc/selinux/vendor_seapp_contexts"
  "etc/selinux/vendor_sepolicy.cil"
)

generate_prop_list_from_image "$1" "$2" VENDOR_SKIP_FILES_AURA
#generate_prop_list_from_image ~/storage/dumps/walleye/walleye-pq1a.190105.004/images/vendor.ext4 vendor-proprietary-files.txt VENDOR_SKIP_FILES_WALLEYE